base_url = "https://axeni.de"
title = "Axenide"
description = "I do things."
theme = "ametrine"
compile_sass = true
build_search_index = true
default_language = "en"
feed_filenames = ["atom.xml", "rss.xml"]

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[languages.es]
title = "Axenide"
description = "Hago cosas."
generate_feeds = true
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
smart_punctuation = true
github_alerts = true

[markdown.highlighting]
theme = "github-dark"

[extra]
discord_user_id = "294856304969908224"
styles = ["custom.css"]
accent_color = "hsl(10, 25%, 65%)"
date_format = "%d %B %Y"
audio_button = true

[extra.meta]
favicon = true

[extra.nav]
icon = "images/avatar.jpg"
links = [
	{ name = "Personal", category = [
    { url = "@/blog/_index.md", name = "Blog", icon = "newspaper-clipping" },
    { url = "@/projects/_index.md", name = "Projects", icon = "cube" },
	] },
]

[extra.nav.es]
links = [
	{ name = "Personal", category = [
    { url = "@/blog/_index.md", name = "Blog", icon = "newspaper-clipping" },
    { url = "@/projects/_index.md", name = "Proyectos", icon = "cube" },
	] },
]

[extra.footer]
copyright = "Â© $YEAR Axenide"
show_powered_by = true
show_timestamp = true
socials = [
    { url = "https://github.com/Axenide", icon = "github" },
    { url = "https://youtube.com/Axenide", icon = "youtube" },
    { url = "https://twitch.tv/Axenide", icon = "twitch" },
    { url = "https://x.com/Axenide", icon = "x" },
    { url = "https://instagram.com/Axenide", icon = "instagram" },
]

[extra.es]
date_locale = "es_ES"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = false
